### ISSUE TITLE
Bricking Cam Pan v1

### ISSUE THREAD

**Issue by gogromat** [kohrar/Wyze-Firmwares#1]
Maybe add to Readme somewhere that latest firmware for Pan v1 kinda [bricks it](https://forums.wyze.com/t/wyze-cam-pan-won-t-factory-reset/253005/18) / [has these issues](https://www.reddit.com/r/Wyze/comments/wzxgue/wyze_cam_1s_recovered_3_of_4_with_the_new/)
Also `latest.bin.zip` and `latest-rtsp.zip` are empty

**Comment by kohrar** [comment]
Thanks for the info. I've updated the firmware files and the readme for the pan v1 and wyze cam v1 in 3b25a9f117fa1bbc4c472d8149f345baa17ac85c.

The latest files are simply symlinks. If you're downloading the repo as a zip or looking at it on something like Windows, it will appear empty.
