### ISSUE TITLE
Instructions wrong to flash WC3

### ISSUE THREAD

**Issue by teredactle** [kohrar/Wyze-Firmwares#2]
First off, thanks for this repository!!!

Please change the fw flashing instructions as they are wrong for v3.

From Wyze directly: https://support.wyze.com/hc/en-us/articles/360031490871-How-to-flash-your-Wyze-Cam-firmware-manually

Flash Firmware for Wyze Cam v3
Wyze Cam v3 files can be found on the [Release Notes](https://support.wyzecam.com/hc/en-us/articles/360024852172) page.
Download a specific version of firmware, For Windows 10: Right-click on the folder and select extract all. For Mac: Just drag and drop the folder, put it on the root directory of your microSD card. For both Mac and Windows, rename the file to **demo_wcv3.bin**.
Power off your camera and insert your microSD card.
Hold the setup button, plug in your USB cable, keep holding the setup button for 3-6 seconds until the light is solid purple, then release the button.
Note: For "Solid Purple" both the blue and red LEDs will be on at once, making it appear to be a solid purple.
Wait for 3-4 minutes. The camera will reboot and change light status during this time.
Once this is done, your camera should be functioning with the original setup. No need to re-setup your camera!

Thanks

**Comment by kohrar** [comment]
Is it just the filename that's incorrect in the readme? If so, the readme has been upated in commit 18e5c6525791c138f7306a1f2a6b201084e28f1b. If it's something else, you're welcome to do a PR and I'll merge it in. Thanks!

**Comment by teredactle** [comment]
Thanks for fixing, yes it was just the filename I guess I should have just said that.
